name: rainbow_manager
description: A Flutter app to manage and edit gradient tiles with hover effects and dark mode.
publish_to: 'none' # Remove if publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI + State
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.2
  reorderables: ^0.6.0

  # Flutter material icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
